export const PLANS = {
  STARTER: {
    name: "Starter",
    description: "For small restaurants just getting started",
    price: {
      monthly: 49.99,
      yearly: 499.99,
    },
    limits: {
      staff: 10,
      menus: 5,
      menuItems: 20,
      tables: 15,
      reservations: 50,
      emails: 100,
      customers: 200,
      waitlist: 50,
      orders: 50,
      storage: 500,
    },
    features: {
      pos: true,
      reporting: true,
      analytics: true,
      api_access: false,
    },
  },
  PREMIUM: {
    name: "Premium",
    description: "For growing restaurants that need more",
    price: {
      monthly: 149.99,
      yearly: 1499.99,
    },
    limits: {
      staff: 50,
      menus: 50,
      menuItems: 500,
      tables: 100,
      reservations: 500,
      emails: 10000,
      customers: 10000,
      waitlist: 200,
      orders: 500,
      storage: 1000,
    },
    features: {
      pos: true,
      reporting: true,
      analytics: true,
      api_access: true,
    },
  },
  ENTERPRISE: {
    name: "Enterprise",
    description: "For large restaurants with complex needs",
    price: {
      monthly: 299.99,
      yearly: 2999.99,
    },
    limits: {
      staff: -1,
      menus: -1,
      menuItems: -1,
      tables: -1,
      reservations: -1,
      emails: -1,
      customers: -1,
      waitlist: -1,
      orders: -1,
      storage: -1,
    },
    features: {
      pos: true,
      reporting: true,
      analytics: true,
      api_access: true,
    },
  },
};
